#redis
redis:
  password: "admin123"  #redis密码
  addr: "127.0.0.1:6379"  #redis地址
  db: 0
  poolsize: 1000

#模式
mode:
  mode: "P" #模式
  bat: false #聊天机器人默认为关闭
  recall: true  #防撤回默认为打开

#服务器
serve:
  port: 5000  #服务器端口
  ws: 5700   #websocket端口

#chaoxing
chaoXing:
  name: ""  #学习通手机号
  password: ""  #密码


